language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich2
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
    - os: osx
      compiler: gcc
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls